name: "Functionality Check"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  schedule:
    - cron: "0 6 * * *"

jobs:
  test-functionality:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: "Setup environment"
        shell: bash
        run: |
          echo "COMMIT_SHA_ABREV=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
          echo "COMMIT_SHA_ABREV: ${{ env.COMMIT_SHA_ABREV }}"
          echo "GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}"
      
      - name: "Setup JDK 11"
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          architecture: x64
          cache: maven
      
      - name: "Run Maven tests"
        run: mvn test -e
      
      - name: "Upload test report"
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-report-${{ env.GITHUB_REF_NAME }}-${{ env.COMMIT_SHA_ABREV }}
          path: library/target/surefire-reports/
